### ISSUE TITLE
Training error:

### ISSUE THREAD

**Issue by jageshmaharjan** [sarnikowski/bert_in_a_flask#5]
I was gonna train on the dataset about StackOverflow, that you provided.
And, I was following the instruction from your README file.

So, I created the docker containers,
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
bert_in_a_flask_api     latest              a40314ea3ac2        30 minutes ago      5.02GB
bert_in_a_flask_dev     latest              06ca0332de71        2 hours ago         4.26GB
........................
```
But I couldn't train however I have a one GPU in my server
`make train TENSORBOARD_PORT=6006 GPU=1`

```
(tfv2) dsdev@dsdev:~/gitrepo/bert_in_a_flask$ make train TENSORBOARD_PORT=6006 GPU=1
unknown flag: --gpus
See 'docker run --help'.
Makefile:19: recipe for target 'train' failed
make: *** [train] Error 125

```

**Comment by sarnikowski** [comment]
Which version of docker are you using ? Notice that for docker >=19.03, which this repo is compatible with, you also need to have `nvidia-container-toolkit` installed. Instructions for installing this can be found in the README at https://github.com/NVIDIA/nvidia-docker.
