### ISSUE TITLE
Always "Bad Request on API server

### ISSUE THREAD

**Issue by loeweh** [sarnikowski/bert_in_a_flask#6]
Hi,

no matter what I am doing, I get a "Bad Request" Response from the API server.

[loewe@linux-2 bert_in_a_flask]$ curl -H "Content-Type: application/json" --request POST --data t1.json http://localhost:5000/predict
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
[loewe@linux-2 bert_in_a_flask]$ cat t1.json
{
    "x": ["Should i use public or private when declaring a variable in a class?", "I get an ImportError everytime i try to import a module in my main.py script"]
}
[loewe@linux-2 bert_in_a_flask]$ 

any idea?

Regards Heiko

**Comment by sarnikowski** [comment]
Your curl command is invalid.
If you want to parse a JSON file to curl, you need to run the curl command like this:
```
curl -H "Content-Type: application/json" --request POST -d @t1.json http://localhost:5000/predict
```
Notice you can also simply parse the JSON directly to the terminal:
```
curl -H "Content-Type: application/json" --request POST --data '{ "x": ["Should i use public or private when declaring a variable in a class?", "I get an ImportError everytime i try to import a module in my main.py script"]}' http://localhost:5000/predict
```
Hope this helps :)
